apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eycart-deployment
  namespace: k-ns
  labels:
    app: eycart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eycart-app
  template:
    metadata:
      labels:
        app: eycart-app
    spec:
      containers:
      - name: eycart-container
        image: muralisocial123/ey-cart:v1.1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

    

