apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fitness-deployment
  namespace: k-ns
  labels:
    app: fitness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
      - name: fitness-container
        image: muralisocial123/fitness-app:v1.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

    

